
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Separator } from "@/components/ui/separator";

const TermsAndConditions = () => {
  return (
    <div class="container">
      <h1>Terms of Service</h1>


      
              <p>Welcome, and thank you for your interest in syraa.live Inc. (<strong>“Syraa,” “we,”</strong> or <strong>“us”</strong>) and our website at <a href="https://www.syraa.live/">www.syraa.live</a>, along with our related websites, hosted applications, and other services provided by us (collectively, the <strong>"Service"</strong>). These Terms of Service are a legally binding contract between you and Syraa regarding your use of the Service.</p>
      
              <h3>PLEASE READ THE FOLLOWING TERMS CAREFULLY:</h3>
              <p class="important-notice">BY CLICKING <strong>"I ACCEPT,"</strong> OR BY OTHERWISE ACCESSING OR USING THE SERVICE, YOU AGREE THAT YOU HAVE READ AND UNDERSTOOD, AND, AS A CONDITION TO YOUR USE OF THE SERVICE, YOU AGREE TO BE BOUND BY, THE FOLLOWING TERMS AND CONDITIONS, INCLUDING SYRAA'S PRIVACY POLICY [<a href="https://syraa.live/privacy">https://syraa.live/privacy</a>] (TOGETHER, THESE <strong>“TERMS”</strong>). If you are not eligible, or do not agree to the Terms, then you do not have our permission to use the Service. <strong>YOUR USE OF THE SERVICE, AND SYRAA'S PROVISION OF THE SERVICE TO YOU, CONSTITUTES AN AGREEMENT BY SYRAA AND BY YOU TO BE BOUND BY THESE TERMS.</strong></p>
      
              <h3>Arbitration NOTICE.</h3>
              <p class="important-notice">Except for certain kinds of disputes described in Section 17 (Dispute Resolution and Arbitration), you agree that disputes arising under these Terms will be resolved by binding, individual arbitration, and <strong>BY ACCEPTING THESE TERMS, YOU AND SYRAA ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN ANY CLASS ACTION OR REPRESENTATIVE PROCEEDING.</strong></p>
      
              <ol>
                  <li>
                      <p class="section-title">Syraa Service Overview.</p>
                      <p>Syraa provides a platform that allows users to build personalized AI chatbots that interface with different sources of information, such as Google Calendar, email, or documents. We also make our software development kit (<strong>"SDK"</strong>) available to developers who would like to write their own agents or plugins to the Service that extend its capabilities (each, a <strong>“Third Party Plugin"</strong>).</p>
                  </li>
                  <li>
                      <p class="section-title">Eligibility.</p>
                      <p>You must be at least 18 years old to use the Service. By agreeing to these Terms, you represent and warrant to us that: (a) you are at least 18 years old; (b) you have not previously been suspended or removed from the Service; and (c) your registration and your use of the Service is in compliance with any and all applicable laws and regulations. If you are an entity, organization, or company, the individual accepting these Terms on your behalf represents and warrants that they have authority to bind you to these Terms and you agree to be bound by these Terms.</p>
                  </li>
                  <li>
                      <p class="section-title">Accounts and Registration.</p>
                      <p>To access features of the Service, you must sign in with either your Google account or GitHub account. When you first sign in, you may be required to provide us with some information about yourself, such as your <strong>[name, email address, or other contact information]</strong>. You agree that the information you provide to us is accurate, complete, and not misleading, and that you will keep it accurate and up to date at all times. You are solely responsible for maintaining the confidentiality of your account and password, and you accept responsibility for all activities that occur under your account. If you believe that your account is no longer secure, then you should immediately notify us at <a href="mailto:legal@syraa.live">legal@syraa.live</a>.</p>
                  </li>
                  <li>
                      <p class="section-title">Permission to Access.</p>
                      <p>When you first sign-in to the Service, the Service will ask your permission to access your system or certain applications, such as Google Calendar and email. You acknowledge and agree that failure to grant the necessary permission to your system or application(s) may affect the performance of the Service and your ability to use certain features of the Service. Syraa is not responsible for any loss or consequences resulting from your failure to grant the necessary permissions under this Section 4 (Permission to Access).</p>
                  </li>
                  <li>
                      <p class="section-title">Licenses</p>
                      <h4>5.1 Limited License.</h4>
                      <p>Subject to your complete and ongoing compliance with these Terms, Syraa grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the Service.</p>
                      <h4>5.2 License Restrictions.</h4>
                      <p>Except and solely to the extent such a restriction is impermissible under applicable law, you may not: (a) reproduce, distribute, publicly display, publicly perform, or create derivative works of the Service; (b) make modifications to the Service; or (c) interfere with or circumvent any feature of the Service, including any security or access control mechanism. If you are prohibited under applicable law from using the Service, then you may not use it. We may impose limits on your use of the Service, for example, in the form of a daily usage limit (e.g., number of Syraa calls per day) or as otherwise specified by us on the Service (<strong>"Usage Limit"</strong>). You will not exceed the Usage Limit of the Service without our prior approval, and we reserve the right to suspend or block your access to the Service in the event you breached any restriction set forth in this Section 5.2 (License Restrictions).</p>
                      <h4>5.3 Feedback.</h4>
                      <p>We respect and appreciate the thoughts and comments from our users If you choose to provide input and suggestions regarding existing functionalities, problems with or proposed modifications or improvements to the Service (<strong>"Feedback"</strong>), then you hereby grant Syraa an unrestricted, perpetual, irrevocable, non-exclusive, fully-paid, royalty-free right and license to exploit the Feedback in any manner and for any purpose, including to improve the Service and create other products and services. We will have no obligation to provide you with attribution for any Feedback you provide to us.</p>
                  </li>
                  <li>
                      <p class="section-title">Ownership; Proprietary Rights.</p>
                      <p>The Service is owned and operated by Syraa. The visual interfaces, graphics, design, compilation, information, data, computer code (including source code or object code), products, software, services, and all other elements of the Service provided by Syraa (collectively, <strong>"Materials"</strong>) are protected by intellectual property and other laws. All Materials included in and related to the Service are the property of Syraa or its third-party licensors. Except as expressly authorized by Syraa, you may not make use of the Materials. There are no implied licenses in these Terms and Syraa reserves all rights to the Materials not granted expressly in these Terms.</p>
                  </li>
                  <li>
                      <p class="section-title">Third-Party Terms</p>
                      <h4>7.1 Third-Party Services and Linked Websites.</h4>
                      <p>Syraa may provide tools through the Service that enable you to export information, including User Content, to third-party services, including through features that allow you to link your account on the Service with an account on the third-party service, such as Twitter or Facebook, or through our implementation of third-party buttons (such as "like" or "share" buttons). By using one of these tools, you hereby authorize that Syraa to transfer that information to the applicable third-party service. Third-party services are not under Syraa's control, and, to the fullest extent permitted by law, Syraa is not responsible for any third-party service's use of your exported information. The Service may also contain links to third-party websites. Linked websites are not under Syraa's control, and Syraa is not responsible for their content. Please be sure to review the terms of use and privacy policy of any third-party services before you share any User Content or information with such third-party services. Once sharing occurs, Syraa will have no control over the information that has been shared.</p>
                      <h4>7.2 Third-Party Software.</h4>
                      <p>The Service may include or incorporate third-party software components that are generally available free of charge under licenses granting recipients broad rights to copy, modify, and distribute those components (<strong>“Third-Party Components"</strong>). Although the Service is provided to you subject to these Terms, nothing in these Terms prevents, restricts, or is intended to prevent or restrict you from obtaining Third-Party Components under the applicable third-party licenses or to limit your use of Third-Party Components under those third-party licenses.</p>
                      <h4>7.3 OpenAI Terms.</h4>
                      <p>The Service is powered by the artificial intelligence (<strong>"AI"</strong>) models offered by OpenAI, including GPT-3 and DALL-E, that generate outputs in response to your input to the Service. By accessing or using the Service, you agree to the following terms of OpenAI (<strong>"OpenAI Terms"</strong>), which are incorporated into these Terms by this reference:</p>
                      <ol>
                          <li>OpenAI Terms of Service available at: <a href="https://openai.com/terms/">https://openai.com/terms/</a></li>
                          <li>OpenAI Privacy Policy available at: <a href="https://openai.com/privacy/">https://openai.com/privacy/</a></li>
                          <li>DALL-E Content Policy available at: <a href="https://labs.openai.com/policies/content-policy">https://labs.openai.com/policies/content-policy</a>.</li>
                      </ol>
                  </li>
                  <li>
                      <p class="section-title">User Content</p>
                      <h4>8.1 User Content Generally.</h4>
                      <p>The Service may permit users to submit, upload, publish, broadcast, or otherwise transmit (<strong>"Post"</strong>) content to the Service, including messages, reviews, photos, inputs, images, folders, data, text, Third Party Plugins, and any other works of authorship or other works (<strong>"User Content"</strong>). User Content also includes the output generated or produced by the Service or a Third Party Plugin in response to your input. You retain any copyright and other proprietary rights that you may hold in the User Content, subject to the licenses granted in these Terms.</p>
                      <h4>8.2 Limited License Grant to Syraa.</h4>
                      <p>By Posting User Content to or via the Service, you grant Syraa a worldwide, non-exclusive, irrevocable, royalty-free, fully paid right and license (with the right to sublicense through multiple tiers) to host, store, transfer, publicly display, publicly perform (including by means of a digital audio transmission), communicate to the public, reproduce, modify for the purpose of formatting for display, create derivative works as authorized in these Terms, and distribute your User Content, in whole or in part, in any media formats and through any media channels, in each instance whether now known or hereafter developed. All of the rights you grant in these Terms are provided on a through-to-the-audience basis, meaning the owners or operators of external services will not have any separate liability to you or any other third party for User Content Posted or otherwise used on external services via the Service. You agree to pay all monies owing to any person or entity resulting from Posting your User Content and from Syraa's exercise of the license set forth in this Section.</p>
                      <h4>8.3 Third Party Plugins.</h4>
                      <p>We may allow you to use our SDK to create Third Party Plugins, subject to your continued compliance with these Terms and any additional terms and policies made available by us in connection with our SDK (<strong>"SDK Terms"</strong>), which are incorporated into these Terms by this reference. You may publish or make available your Third Party Plugins for other users of the Service to incorporate into their chatbots. Once published, your Third Party Plugins will be available to all users of the Service. You may disable or disconnect your Third Party Plugin any time through the Syraa Agent Dashboard or by contacting us at <a href="mailto:legal@syraa.live">legal@syraa.live</a>.</p>
                      <h4>8.4 You Must Have Rights to the Content You Post; User Content Representations and Warranties.</h4>
                      <p>You must not Post User Content if you are not the owner of or are not fully authorized to grant rights in all of the elements of that User Content. Syraa disclaims any and all liability in connection with User Content. You are solely responsible for your User Content and the consequences of providing User Content via the Service. By providing User Content via the Service, you affirm, represent, and warrant to us that:</p>
                      <p>(a) you are the creator and owner of the User Content, or have the necessary licenses, rights, consents, and permissions to authorize Syraa and users of the Service to use and distribute your User Content as necessary to exercise the licenses granted by you in this Section, in the manner contemplated by Syraa, the Service, and these Terms;</p>
                      <p>(b) you will not create, publish, distribute, or otherwise make available any Third Party Plugin that: (i) generates or returns content that infringes, misappropriates, or violates third-party rights, including intellectual property rights and rights of privacy and publicity; (ii) generates content that is harmful, pornographic, inaccurate, misleading, or otherwise objectionable or offensive; or (iii) violates any applicable law or regulations;</p>
                      <p>(c) your User Content, and the Posting or other use of your User Content as contemplated by these Terms, does not and will not: (i) infringe, violate, misappropriate, or otherwise breach any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property, contract, or proprietary right; (ii) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person; or (iii) cause Syraa to violate any law or regulation or require us to obtain any further licenses from or pay any royalties, fees, compensation or other amounts or provide any attribution to any third parties; and</p>
                      <p>(d) your User Content could not be deemed by a reasonable person to be objectionable, profane, indecent, pornographic, harassing, threatening, embarrassing, hateful, or otherwise inappropriate.</p>
                      <h4>8.5 User Content Disclaimer.</h4>
                      <p>We are under no obligation to edit or control User Content that you or other users Post and will not be in any way responsible or liable for User Content, including Third Party Plugin published by other users. Syraa may, however, at any time and without prior notice, screen, remove, edit, or block any User Content that in our sole judgment violates these Terms, is alleged to violate the rights of third parties, or is otherwise objectionable. You understand that, when using the Service, you may have access to Third Party Plugins from a variety of sources and acknowledge that Third Party Plugins may generate content that is inaccurate, offensive, indecent, or objectionable. You agree to waive, and do waive, any legal or equitable right or remedy you have or may have against Syraa with respect to User Content, including Third Party Plugins. If notified by a user or content owner that User Content allegedly does not conform to these Terms, we may investigate the allegation and determine in our sole discretion whether to remove the User Content, which we reserve the right to do at any time and without notice. For clarity, Syraa does not permit infringing activities on the Service.</p>
                      <h4>8.6 Monitoring Content.</h4>
                      <p>Syraa does not control and does not have any obligation to monitor: (a) User Content; (b) any content made available by third parties; or (c) the use of the Service by its users. You acknowledge and agree that Syraa reserves the right to, and may from time to time, monitor any and all information transmitted or received through the Service for operational and other purposes. If at any time Syraa chooses to monitor the content, then Syraa still assumes no responsibility or liability for content or any loss or damage incurred as a result of the use of content. During monitoring, information may be examined, recorded, copied, and used in accordance with our Privacy Policy (defined below). Syraa may block, filter, mute, remove or disable access to any User Content uploaded to or transmitted through the Service without any liability to the user who Posted such User Content to the Service or to any other users of the Service. Syraa may remove or block any Third Party Plugin that is, in Syraa's sole discretion, in violation of these Terms or applicable laws (even if it has been accepted by Syraa or made available to other users on the Service), and Syraa reserves the right to ban or block the developer of such Third Party Plugin from the Service.</p>
                      <h4>8.7 Content Filter.</h4>
                      <p>Certain features of our Service are based on AI models (including OpenAI's models) and we do not control their outputs. We reserve the right to implement content filter and/or other moderation tools to monitor and remove the outputs generated by Third Party Plugins if, in our sole discretion, they fail to comply with these Terms or OpenAI Terms.</p>
                  </li>
                  <li>
                      <p class="section-title">Communications</p>
                      <h4>9.1 Email.</h4>
                      <p>We may send you emails concerning our products and services, as well as those of third parties. You may opt out of promotional emails by following the unsubscribe instructions in the promotional email itself.</p>
                  </li>
                  <li>
                      <p class="section-title">Prohibited Conduct.</p>
                      <p>BY USING THE SERVICE, YOU AGREE NOT TO:</p>
                      <p class="sub-section-title">10.1</p><p>use the Service for any illegal purpose or in violation of any local, state, national, or international law;</p>
                      <p class="sub-section-title">10.2</p><p>use the Service to generate content that: (a) harasses, bullies, or threatens any individual; (b) promotes hate, discrimination, self-harm, or violence; (c) is obscene or pornographic (excluding sex education and wellness); (d) attempts to influence the political process or is intended to be used for campaigning purposes; (f) attempts to defraud individuals or is otherwise false or misleading; or (g) is ransomware, keyloggers, viruses, or other harmful software or code;</p>
                      <p class="sub-section-title">10.3</p><p>violate, encourage others to violate, or provide instructions on how to violate, any right of a third party, including by infringing or misappropriating any third-party intellectual property right;</p>
                      <p class="sub-section-title">10.4</p><p>access, search, or otherwise use any portion of the Service through the use of any engine, software, tool, agent, device, or mechanism (including spiders, robots, crawlers, and data mining tools) other than the software or search agents provided by Syraa;</p>
                      <p class="sub-section-title">10.5</p><p>interfere with security-related features of the Service, including by: (i) disabling or circumventing features that prevent or limit use, printing or copying of any content; or (ii) reverse engineering or otherwise attempting to discover the source code of any portion of the Service except to the extent that the activity is expressly permitted by applicable law;</p>
                      <p class="sub-section-title">10.6</p><p>interfere with the operation of the Service or any user's enjoyment of the Service, including by: (i) uploading or otherwise disseminating any virus, adware, spyware, worm, or other malicious code; (ii) making any unsolicited offer or advertisement to another user of the Service; (iii) collecting personal information about another user or third party without consent; or (iv) interfering with or disrupting any network, equipment, or server connected to or used to provide the Service;</p>
                      <p class="sub-section-title">10.7</p><p>perform any fraudulent activity including impersonating any person or entity, claiming a false affiliation or identity, accessing any other Service account without permission;</p>
                      <p class="sub-section-title">10.8</p><p>sell or otherwise transfer the access granted under these Terms or any Materials (as defined in Section 6 (Ownership; Proprietary Rights)) or any right or ability to view, access, or use any Materials; or</p>
                      <p class="sub-section-title">10.9</p><p>attempt to do any of the acts described in this Section 10 (Prohibited Conduct) or assist or permit any person in engaging in any of the acts described in this Section 10 (Prohibited Conduct).</p>
                  </li>
                  <li>
                      <p class="section-title">Intellectual Property Rights Protection</p>
                      <h4>11.1 Respect of Third Party Rights.</h4>
                      <p>Syraa respects the intellectual property rights of others, takes the protection of intellectual property rights very seriously, and asks users of the Service to do the same.</p>
                      <h4>11.2 Procedure for Reporting Claimed Infringement.</h4>
                      <p>If you believe that any content made available on or through the Service has been used or exploited in a manner that infringes an intellectual property right you own or control, then please promptly send a written <strong>“Notification of Claimed Infringement"</strong> to the Designated Agent identified above containing the following information:</p>
                      <p>(a) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other right being infringed;</p>
                      <p>(b) a description of the copyrighted work or other intellectual property right that you claim has been infringed;</p>
                      <p>(c) a description of the material that you claim is infringing and where it is located on the Service;</p>
                      <p>(d) your address, telephone number, and email address;</p>
                      <p>(e) a statement by you that you have a good faith belief that the use of the materials on the Service of which you are complaining is not authorized by the copyright or other intellectual property right owner, its agent, or the law; and</p>
                      <p>(f) a statement by you that the above information in your notice is accurate and that, under penalty of perjury, you are the copyright or other intellectual property right owner or authorized to act on the copyright or intellectual property owner's behalf.</p>
                      <h4>11.3 Repeat Infringers.</h4>
                      <p>Syraa's policy is to: (a) remove or disable access to material that Syraa believes in good faith, upon notice from an intellectual property rights owner or authorized agent, is infringing the intellectual property rights of a third party by being made available through the Service; and (b) in appropriate circumstances, to terminate the accounts of and block access to the Service by any user who repeatedly or egregiously infringes other people's copyright or other intellectual property rights. Syraa will terminate the accounts of users that are determined by Syraa to be repeat infringers. Syraa reserves the right, however, to suspend or terminate accounts of users in our sole discretion.</p>
                      <h4>11.4 Counter Notification.</h4>
                      <p>If you receive a notification from Syraa that material made available by you on or through the Service has been the subject of a Notification of Claimed Infringement, then you will have the right to provide Syraa with what is called a <strong>"Counter Notification."</strong> To be effective, a Counter Notification must be in writing, provided to Syraa's Designated Agent through one of the methods, and include substantially the following information:</p>
                      <p>(a) your physical or electronic signature;</p>
                      <p>(b) identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;</p>
                      <p>(c) a statement under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; and</p>
                  </li>
                   <li>
                      <p class="section-title">Modification of Terms.</p>
                      <p>We may, from time to time, change these Terms. Please check these Terms periodically for changes. Revisions will be effective immediately except that, for existing users, material revisions will be effective 30 days after posting or notice to you of the revisions unless otherwise stated. We may require that you accept modified Terms in order to continue to use the Service. If you do not agree to the modified Terms, then you should remove your User Content and discontinue your use of the Service. Except as expressly permitted in this Section 12 (Modification of Terms), these Terms may be amended only by a written agreement signed by authorized representatives of the parties to these Terms.</p>
                  </li>
                  <li>
                      <p class="section-title">Term, Termination, and Modification of the Service</p>
                      <h4>13.1 Term.</h4>
                      <p>These Terms are effective beginning when you accept the Terms or first download, install, access, or use the Service, and ending when terminated as described in Section 13.2 (Termination).</p>
                      <h4>13.2 Termination.</h4>
                      <p>If you violate any provision of these Terms, then your authorization to access the Service and these Terms automatically terminate. In addition, Syraa may, at its sole discretion, terminate these Terms or your account on the Service, or suspend or terminate your access to the Service, at any time for any reason or no reason, with or without notice, and without any liability to you arising from such termination. You may terminate your account and these Terms at any time by deleting your account on the Syraa User Dashboard or by contacting customer service at <a href="mailto:legal@syraa.live">legal@syraa.live</a>.</p>
                      <h4>13.3 Effect of Termination.</h4>
                      <p>Upon termination of these Terms: (a) your license rights will terminate and you must immediately cease all use of the Service; (b) you will no longer be authorized to access your account or the Service; and (c) all definitions and Sections 5.3 (Feedback), 6 (Ownership; Proprietary Rights), 11 (Intellectual Property Rights Protection), 13.3 (Effect of Termination), 14 (Indemnity), 15 (Disclaimers; No Warranties by Syraa), 16 (Limitation of Liability), 17 (Dispute Resolution and Arbitration), and 18 (Miscellaneous) will survive. You are solely responsible for retaining copies of any User Content you Post to the Service since upon termination of your account, you may lose access rights to any User Content you Posted to the Service. If your account has been terminated for a breach of these Terms, then you are prohibited from creating a new account on the Service using a different name, email address or other forms of account verification.</p>
                      <h4>13.4 Modification of the Service.</h4>
                      <p>Syraa reserves the right to modify or discontinue all or any portion of the Service at any time (including by limiting or discontinuing certain features of the Service), temporarily or permanently, without notice to you. Syraa will have no liability for any change to the Service, including any paid-for functionalities of the Service, or any suspension or termination of your access to or use of the Service. You should retain copies of any User Content you Post to the Service so that you have permanent copies in the event the Service is modified in such a way that you lose access to User Content you Posted to the Service.</p>
                  </li>
                  <li>
                      <p class="section-title">Indemnity.</p>
                      <p>To the fullest extent permitted by law, you are responsible for your use of the Service, and you will defend and indemnify Syraa, its affiliates and their respective shareholders, directors, managers, members, officers, employees, consultants, and agents (together, the <strong>"Syraa Entities"</strong>) from and against every claim brought by a third party, and any related liability, damage, loss, and expense, including attorneys' fees and costs, arising out of or connected with: (1) your unauthorized use of, or misuse of, the Service; (2) your violation of any portion of these Terms, any representation, warranty, or agreement referenced in these Terms, or any applicable law or regulation; (3) your violation of any third-party right, including any intellectual property right or publicity, confidentiality, other property, or privacy right; or (4) any dispute or issue between you and any third party. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you (without limiting your indemnification obligations with respect to that matter), and in that case, you agree to cooperate with our defense of those claims.</p>
                  </li>
                  <li>
                      <p class="section-title">Disclaimers; No Warranties by Syraa</p>
                      <h4>15.1</h4>
                      <p>THE SERVICE AND ALL MATERIALS AND CONTENT AVAILABLE THROUGH THE SERVICE (INCLUDING THE SDK) ARE PROVIDED "AS IS" AND ON AN "AS AVAILABLE" BASIS. Syraa DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, RELATING TO THE SERVICE AND ALL MATERIALS AND CONTENT AVAILABLE THROUGH THE SERVICE, INCLUDING: (a) ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, OR NON-INFRINGEMENT; AND (b) ANY WARRANTY ARISING OUT OF COURSE OF DEALING, USAGE, OR TRADE. Syraa DOES NOT WARRANT THAT THE SERVICE OR ANY PORTION OF THE SERVICE, OR ANY MATERIALS OR CONTENT OFFERED THROUGH THE SERVICE, WILL BE UNINTERRUPTED, SECURE, OR FREE OF ERRORS, VIRUSES, OR OTHER HARMFUL COMPONENTS, AND Syraa DOES NOT WARRANT THAT ANY OF THOSE ISSUES WILL BE CORRECTED. IN PARTICULAR, SYRAA IS NOT RESPONSIBLE for and hereby EXPRESSLY disclaim ANY AND all liabilitIES with respect to: (a) the output generated by the Service or a third party plugin IN RESPONSE TO YOUR INPUT, INCLUDING ANY ERRORS OR MISTAKES CONTAINED IN SUCH OUTPUT; (b) your use of a third party plugin MADE AVAILABLE TO YOU THROUGH THE SERVICE; AND (C) Your acces to or use of the sdk. FURTHER, Syraa is not responsible for any loss or consequences resulting from your failure to grant the necessary permissions TO YOUR SYSTEM under Section 4 (Permission to Access).</p>
                      <h4>15.2</h4>
                      <p>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, ΟΒΤΑΙΝED BY YOU FROM THE SERVICE OR Syraa ENTITIES OR ANY MATERIALS OR CONTENT AVAILABLE THROUGH THE SERVICE WILL CREATE ANY WARRANTY REGARDING ANY OF THE Syraa ENTITIES OR THE SERVICE THAT IS NOT EXPRESSLY STATED IN THESE TERMS. WE ARE NOT RESPONSIBLE FOR ANY DAMAGE THAT MAY RESULT FROM THE SERVICE, ANY USER CONTENT, AND YOUR DEALING WITH ANY OTHER SERVICE USER. YOU UNDERSTAND AND AGREE THAT YOU USE ANY PORTION OF THE SERVICE AND ANY USER CONTENT AT YOUR OWN DISCRETION AND RISK, AND THAT WE ARE NOT RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY (INCLUDING YOUR COMPUTER SYSTEM OR MOBILE DEVICE USED IN CONNECTION WITH THE SERVICE) OR ANY LOSS OF DATA, INCLUDING USER CONTENT.</p>
                      <h4>15.3</h4>
                      <p>THE LIMITATIONS, EXCLUSIONS AND DISCLAIMERS IN THIS SECTION 15 (Disclaimers; No Warranties by Syraa) APPLY TO THE FULLEST EXTENT PERMITTED BY LAW. Syraa does not disclaim any warranty or other right that Syraa is prohibited from disclaiming under applicable law.</p>
                  </li>
                  <li>
                      <p class="section-title">Limitation of Liability</p>
                      <h4>16.1</h4>
                      <p>TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL THE Syraa ENTITIES BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES (INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL, OR ANY OTHER INTANGIBLE LOSS) ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF, OR YOUR INABILITY TO ACCESS OR USE, THE SERVICE OR ANY MATERIALS OR CONTENT ON THE SERVICE, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT ANY Syraa ENTITY HAS BEEN INFORMED OF THE POSSIBILITY OF DAMAGE.</p>
                      <h4>16.2</h4>
                      <p>EXCEPT AS PROVIDED IN SECTIONS 17.5 (Commencing Arbitration) AND 17.7 (ARBITRATION RELIEF) AND TO THE FULLEST EXTENT PERMITTED BY LAW, THE AGGREGATE LIABILITY OF THE Syraa ENTITIES TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE USE OF OR ANY INABILITY TO USE ANY PORTION OF THE SERVICE OR OTHERWISE UNDER THESE TERMS, WHETHER IN CONTRACT, TORT, OR OTHERWISE, IS LIMITED TO US$100.</p>
                      <h4>16.3</h4>
                      <p>EACH PROVISION OF THESE TERMS THAT PROVIDES FOR A LIMITATION OF LIABILITY, DISCLAIMER OF WARRANTIES, OR EXCLUSION OF DAMAGES IS INTENDED TO AND DOES ALLOCATE THE RISKS BETWEEN THE PARTIES UNDER THESE TERMS. THIS ALLOCATION IS AN ESSENTIAL ELEMENT OF THE BASIS OF THE BARGAIN BETWEEN THE PARTIES. EACH OF THESE PROVISIONS IS SEVERABLE AND INDEPENDENT OF ALL OTHER PROVISIONS OF THESE TERMS. THE LIMITATIONS IN THIS SECTION 16 (LIMITATION OF LIABILITY) WILL APPLY EVEN IF ANY LIMITED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
                  </li>
                  <li>
                      <p class="section-title">Dispute Resolution and Arbitration</p>
                      <h4>17.1 Generally.</h4>
                      <p>Except as described in Section 17.2 (Exceptions) and 17.3 (Opt-Out), you and Syraa agree that every dispute arising in connection with these Terms, the Service, or communications from us will be resolved through binding arbitration. Arbitration uses a neutral arbitrator instead of a judge or jury, is less formal than a court proceeding, may allow for more limited discovery than in court, and is subject to very limited review by courts. This agreement to arbitrate disputes includes all claims whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and regardless of whether a claim arises during or after the termination of these Terms. Any dispute relating to the interpretation, applicability, or enforceability of this binding arbitration agreement will be resolved by the arbitrator.</p>
                      <h3 class="important-notice">YOU UNDERSTAND AND AGREE THAT, BY ENTERING INTO THESE TERMS, YOU AND SYRAA ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION.</h3>
                      <h4>17.2 Exceptions.</h4>
                      <p>Although we are agreeing to arbitrate most disputes between us, nothing in these Terms will be deemed to waive, preclude, or otherwise limit the right of either party to: (a) bring an individual action in small claims court; (b) pursue an enforcement action through the applicable federal, state, or local agency if that action is available; (c) seek injunctive relief in a court of law in aid of arbitration; or (d) to file suit in a court of law to address an intellectual property infringement claim.</p>
                      <h4>17.3 Opt-Out.</h4>
                      <p>If you do not wish to resolve disputes by binding arbitration, you may opt out of the provisions of this Section 17 (Dispute Resolution and Arbitration) within 30 days after the date that you agree to these Terms by sending a letter to <a href="mailto:legal@syraa.live">legal@syraa.live</a>, Attention: Legal Department - Arbitration Opt-Out, [Company Postal Address] that specifies: your full legal name, the email address associated with your account on the Service, and a statement that you wish to opt out of arbitration (<strong>"Opt-Out Notice"</strong>). Once Syraa receives your Opt-Out Notice, this Section 17 (Dispute Resolution and Arbitration) will be void and any action arising out of these Terms will be resolved as set forth in Section 18.2 (Governing Law). The remaining provisions of these Terms will not be affected by your Opt-Out Notice.</p>
                  </li>
                  <li>
                      <p class="section-title">Miscellaneous</p>
                      <h4>18.1 General Terms.</h4>
                      <p>These Terms, including the Privacy Policy and any other agreements expressly incorporated by reference into these Terms, are the entire and exclusive understanding and agreement between you and Syraa regarding your use of the Service. You may not assign or transfer these Terms or your rights under these Terms, in whole or in part, by operation of law or otherwise, without our prior written consent. We may assign these Terms and all rights granted under these Terms, including with respect to your User Content, at any time without notice or consent. The failure to require performance of any provision will not affect our right to require performance at any other time after that, nor will a waiver by us of any breach or default of these Terms, or any provision of these Terms, be a waiver of any subsequent breach or default or a waiver of the provision itself. Use of Section headers in these Terms is for convenience only and will not have any impact on the interpretation of any provision. Throughout these Terms the use of the word "including" means "including but not limited to." If any part of these Terms is held to be invalid or unenforceable, then the unenforceable part will be given effect to the greatest extent possible, and the remaining parts will remain in full force and effect.</p>
                      <h4>18.2 Governing Law.</h4>
                      <p>These Terms are governed by the laws of India without regard to conflict of law principles. You and Syraa submit to the personal and exclusive jurisdiction of the state courts located within New Delhi, India for resolution of any lawsuit or court proceeding permitted under these Terms.</p>
                      <h4>18.3 Privacy Policy.</h4>
                      <p>Please read the Syraa Privacy Policy [<a href="https://syraa.live/privacy">https://Syraa.live/privacy</a>] (the <strong>"Privacy Policy"</strong>) carefully for information relating to our collection, use, storage, and disclosure of your personal information. The Syraa Privacy Policy is incorporated by this reference into, and made a part of, these Terms.</p>
                      <h4>18.4 Additional Terms.</h4>
                      <p>Your use of the Service is subject to all additional terms, policies, rules, or guidelines applicable to the Service or certain features of the Service that we may post on or link to from the Service (the <strong>"Additional Terms"</strong>). All Additional Terms are incorporated by this reference into, and made a part of, these Terms.</p>
                      <h4>18.5 Consent to Electronic Communications.</h4>
                      <p>By using the Service, you consent to receiving certain electronic communications from us as further described in our Privacy Policy. Please read our Privacy Policy to learn more about our electronic communications practices. You agree that any notices, agreements, disclosures, or other communications that we send to you electronically will satisfy any legal communication requirements, including that those communications be in writing.</p>
                      <h4>18.8 No Support.</h4>
                      <p>We are under no obligation to provide support for the Service. In instances where we may offer support, the support will be subject to published policies.</p>
                      <h4>18.9 International Use.</h4>
                      <p>The Service is intended for visitors located within the United States. We make no representation that the Service is appropriate or available for use outside of the United States. Access to the Service from countries or territories or by individuals where such access is illegal is prohibited.</p>
                  </li>
              </ol>
              <p><a href="https://www.syraa.live">Back to Home</a></p>
        </div>
  );
};

export default TermsAndConditions;
